use SQLProjekatNFL;
GO
INSERT dbo.Igrac
VALUES
('Kyler', 'Murray', 1, 'QB', 1),
('Kenyan', 'Drake', 1, 'RB', 1),
('DeAndre', 'Hopkins', 1, 'WR', 1),
('Matt', 'Ryan', 2, 'QB', 1),
('Todd', 'Gurley', 2, 'RB', 1),
('Julio', 'Jones', 2, 'WE', 1),
('Lamar', 'Jackson', 3, 'QB', 1),
('Gus', 'Edwards', 3, 'RB', 1),
('Marquise','Brown', 3, 'WR', 1),
('Josh', 'Allen', 4, 'QB', 1),
('Devin', 'Singletary', 4, 'RB', 1),
('Stefon','Diggs', 4, 'WR', 1),
('Teddy', 'Bridgewater', 5, 'QB', 1),
('Mike', 'Davis', 5, 'RB', 1),
('Curtis','Samuel', 5, 'WR', 1),
('Mitchell', 'Trubisky', 6, 'QB', 1),
('David', 'Montgomery', 6, 'RB', 1),
('Allen','Robinson', 6, 'WR', 1),
('Joe', 'Burrow', 7, 'QB', 0),
('Giovani', 'Bernard', 7, 'RB', 1),
('A.J','Green', 7, 'WR', 1),
('Baker', 'Mayfield', 8, 'QB', 1),
('Nick', 'Chubb', 8, 'RB', 1),
('Odell','Beckham Jr.', 8, 'WR', 1),
('Dak', 'Prescott', 9, 'QB', 0),
('Ezekiel', 'Elliott', 9, 'RB', 1),
('Amari','Cooper', 9, 'WR', 1),
('Drew', 'Lock', 10, 'QB', 1),
('Melvin', 'Gordon', 10, 'RB', 1),
('Tim','Patrick', 10, 'WR', 1),
('Matthew', 'Stafford', 11, 'QB', 1),
('Adrian', 'Peterson', 11, 'RB', 1),
('Marvin','Jones', 11, 'WR', 1),
('Aaron', 'Rodgers', 12, 'QB', 1),
('Aaron', 'Jones', 12, 'RB', 1),
('Davante','Adams', 12, 'WR', 1),
('Deshaun', 'Watson', 13, 'QB', 1),
('David', 'Johnson', 13, 'RB', 1),
('Keke','Coutee', 13, 'WR', 1),
('Philip', 'Rivers', 14, 'QB', 1),
('Jonathan', 'Taylor', 14, 'RB', 1),
('T.Y.','Hilton', 14, 'WR', 1),
('Mike', 'Glennon', 15, 'QB', 1),
('Dare', 'Ogunbowale', 15, 'RB', 1),
('Chris','Conley', 15, 'WR', 1),
('Patrick', 'Mahomes', 16, 'QB', 1),
('Clyde', 'Edwards-Helaire', 16, 'RB', 1),
('Tyreek','Hill', 16, 'WR', 1),
('Justin', 'Herbert', 17, 'QB', 1),
('Austin', 'Ekeler', 17, 'RB', 1),
('Mike','Williams', 17, 'WR', 1),
('Jared', 'Goff', 18, 'QB', 1),
('Malcolm', 'Brown', 18, 'RB', 1),
('Cooper','Kupp', 18, 'WR', 1),
('Tua', 'Tagovailoa', 19, 'QB', 1),
('Myles', 'Gaskin', 19, 'RB', 1),
('DeVante','Parker', 19, 'WR', 1),
('Kirk', 'Cousins', 20, 'QB', 1),
('Dalvin', 'Cook', 20, 'RB', 1),
('Adam','Thielen', 20, 'WR', 1),
('Cam', 'Newton', 21, 'QB', 1),
('Sony', 'Michel', 21, 'RB', 1),
('Julian','Edelman', 21, 'WR', 1),
('Drew', 'Brees', 22, 'QB', 1),
('Alvin', 'Kamara', 22, 'RB', 1),
('Emmanuel','Sanders', 22, 'WR', 1),
('Daniel', 'Jones', 23, 'QB', 1),
('Wayne', 'Gallman', 23, 'RB', 1),
('Darius','Slayton', 23, 'WR', 1),
('Sam', 'Darnold', 24, 'QB', 1),
('Frank', 'Gore', 24, 'RB', 1),
('Breshad','Perriman', 24, 'WR', 1),
('Derek', 'Carr', 25, 'QB', 1),
('Josh', 'Jacobs', 25, 'RB', 1),
('Hunter','Renfrow', 25, 'WR', 1),
('Carson', 'Wentz', 26, 'QB', 1),
('Miles', 'Sanders', 26, 'RB', 1),
('Greg','Ward', 26, 'WR', 1),
('Ben', 'Roethlisberger', 27, 'QB', 1),
('James', 'Conner', 27, 'RB', 1),
('JuJu','Smith-Schuster', 27, 'WR', 1),
('Jimmy', 'Garappolo', 28, 'QB', 0),
('Jerick', 'McKinnon', 28, 'RB', 1),
('Kendrick','Bourne', 28, 'WR', 1),
('Russell', 'Wilson', 29, 'QB', 1),
('Carlos', 'Hyde', 29, 'RB', 1),
('Tyler','Lockett', 29, 'WR', 1),
('Tom', 'Brady', 30, 'QB', 1),
('Ronald', 'Jones', 30, 'RB', 1),
('Mike','Evans', 30, 'WR', 1),
('Ryan', 'Tannehill', 31, 'QB', 1),
('Derrick', 'Henry', 31, 'RB', 1),
('A.J.','Brown', 31, 'WR', 1),
('Alex', 'Smith', 32, 'QB', 0),
('J.D.', 'McKissic', 32, 'RB', 1),
('Terry','McLaurin', 32, 'WR', 1);
SELECT * FROM dbo.Igrac
GO