USE [SQLProjekatNFL]
GO

/****** Object:  Table [dbo].[Ugovor]    Script Date: 2/1/2021 9:44:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Ugovor](
	[UgovorID] [int] IDENTITY(1,1) NOT NULL,
	[IgracID] [int] NOT NULL,
	[VrednostUgovora] [int] NOT NULL,
	[DuzinaUgovora] [int] NOT NULL,
 CONSTRAINT [PK_Ugovor] PRIMARY KEY CLUSTERED 
(
	[UgovorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Ugovor]  WITH CHECK ADD  CONSTRAINT [FK_Ugovor_Igrac] FOREIGN KEY([IgracID])
REFERENCES [dbo].[Igrac] ([IgracID])
GO

ALTER TABLE [dbo].[Ugovor] CHECK CONSTRAINT [FK_Ugovor_Igrac]
GO

