USE [SQLProjekatNFL]
GO

/****** Object:  Table [dbo].[Igrac]    Script Date: 1/25/2021 9:58:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Igrac](
	[IgracID] [int] IDENTITY(1,1) NOT NULL,
	[Ime] [nvarchar](30) NOT NULL,
	[Prezime] [nvarchar](40) NOT NULL,
	[EkipaID] [int] NOT NULL,
	[Pozicija] [nvarchar](50) NOT NULL,
	[Status] [bit] NOT NULL,
 CONSTRAINT [PK_Igrac] PRIMARY KEY CLUSTERED 
(
	[IgracID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Igrac]  WITH CHECK ADD  CONSTRAINT [FK_Igrac_Ekipa] FOREIGN KEY([EkipaID])
REFERENCES [dbo].[Ekipa] ([EkipaID])
GO

ALTER TABLE [dbo].[Igrac] CHECK CONSTRAINT [FK_Igrac_Ekipa]
GO

