USE [SQLProjekatNFL]
GO

/****** Object:  Table [dbo].[Grad]    Script Date: 1/25/2021 9:58:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Grad](
	[GradID] [int] IDENTITY(1,1) NOT NULL,
	[State] [nvarchar](50) NOT NULL,
	[NazivGrada] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Grad] PRIMARY KEY CLUSTERED 
(
	[GradID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

